// Central typed icon exports to limit what we import application-wide.
// This still uses lucide-react's types (no per-file path issues) while
// providing a single place to manage icon usage and fallback handling.
export {
  Package,
  Diamond,
  MapPin,
  MessageCircle,
  Clock,
  Heart,
  Disc,
  Sparkles,
  Zap,
  Users,
  Wrench,
  Shield,
  Star,
  CheckCircle,
  TrendingUp,
  Calculator,
  AlertCircle,
  Search,
  ChevronDown,
  Tag,
  DollarSign,
  HelpCircle,
  ThumbsUp,
  Quote,
  Award,
  ArrowRight,
  // Additional icons used across components
  User,
  Calendar,
  ChevronLeft,
  ChevronRight,
  Pause,
  Play,
  Check,
  Loader,
  ShoppingCart,
  ShoppingBag,
  MessageSquarePlus,
  ExternalLink,
} from "lucide-react";
